version: '3.9'
services: 
  app:
    container_name: node-mongo
    restart: always
    build: .
    ports: 
      - '8000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27027:27027'