#           #
#   TODOS   #
#           #

###

POST https://localhost:3000/planner/todo HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

{
    "name": "TEST",
    "text": "TEST",
    "datetime": "2021-02-20T00:00:00",
    "completed": false
}

###

GET https://localhost:3000/planner/todo HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

GET https://localhost:3000/planner/todo/602a320968a7c45c997b77c2 HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

DELETE https://localhost:3000/planner/todo/602a324968a7c45c997b77c5 HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

PATCH https://localhost:3000/planner/todo/602a324968a7c45c997b77c5 HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

{
    "name": "11111",
    "text": "22222",
    "datetime": "2021-02-20T00:10:00",
    "completed": true
}

#              #
#   MEETINGS   #
#              #

###

POST https://localhost:3000/planner/meeting HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3ARJ3v5goxiYo1FO_cOLFSIJcF4Y52J9d6.fXDQDFVDL2IovrAEEtZ9SMLi9gE4ZBJaxwvCQWeKsX0

{
    "name": "TEST 222",
    "text": "TEST 222",
    "datetime": "2021-02-20T00:00:00",
    "completed": false
}

###

GET https://localhost:3000/planner/meeting HTTP/1.1
Cookie: connect.sid=s%3ARJ3v5goxiYo1FO_cOLFSIJcF4Y52J9d6.fXDQDFVDL2IovrAEEtZ9SMLi9gE4ZBJaxwvCQWeKsX0

###

GET https://localhost:3000/planner/meeting/602be6c4cf9e886686e5f110 HTTP/1.1
Cookie: connect.sid=s%3Aj6_aq47osJvGWE3t_GbfqFHwnxerd3AR.a7n2FJ7UfVMFV7yIrs7BCa308pRy41V8qWJvFbQakIA

###

DELETE https://localhost:3000/planner/meeting/602be6c4cf9e886686e5f110 HTTP/1.1
Cookie: connect.sid=s%3Aj6_aq47osJvGWE3t_GbfqFHwnxerd3AR.a7n2FJ7UfVMFV7yIrs7BCa308pRy41V8qWJvFbQakIA

###

PATCH https://localhost:3000/planner/meeting/602be6c4cf9e886686e5f110 HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3Aj6_aq47osJvGWE3t_GbfqFHwnxerd3AR.a7n2FJ7UfVMFV7yIrs7BCa308pRy41V8qWJvFbQakIA

{
    "name": "11111",
    "text": "22222",
    "datetime": "2021-02-20T00:10:00",
    "completed": true
}

#          #
#   PLAN   #
#          #

###

POST https://localhost:3000/planner/plan HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

{
    "name": "TEST PLAN",
    "text": "TEST",
    "time": "00:00:00",
    "completed": false
}

###

GET https://localhost:3000/planner/plan HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

GET https://localhost:3000/planner/plan/602a3d6db1d8f3779527656a HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

DELETE https://localhost:3000/planner/plan/602a3d6db1d8f3779527656a HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

PATCH https://localhost:3000/planner/plan/602a3d6db1d8f3779527656a HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

{
    "name": "11111",
    "text": "22222",
    "time": "00:10:00",
    "completed": true
}

#           #
#   NOTES   #
#           #

###

POST https://localhost:3000/notes HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

{
    "name": "TEST Note 2",
    "text": "TEST"
}

###

GET https://localhost:3000/notes HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

GET https://localhost:3000/notes/note/602a9ffc4b77ef505c08a12b HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

DELETE https://localhost:3000/notes/note/602a9ffc4b77ef505c08a12b HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

PATCH https://localhost:3000/notes/note/602a9ffc4b77ef505c08a12b HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

{
    "name": "11111",
    "text": "22222",
    "time": "00:10:00",
    "completed": true
}

#              #
#   MEETINGS   #
#              #

###

POST https://localhost:3000/planner/meeting HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

{
    "name": "TEST",
    "text": "TEST",
    "datetime": "2021-02-20T00:00:00",
    "completed": false
}

###

GET https://localhost:3000/planner/meeting HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

GET https://localhost:3000/planner/meeting/602a352074bdc969f5d41788 HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

DELETE https://localhost:3000/planner/meeting/602a352074bdc969f5d41788 HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

PATCH https://localhost:3000/planner/meeting/602a352074bdc969f5d41788 HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

{
    "name": "11111",
    "text": "22222",
    "datetime": "2021-02-20T00:10:00",
    "completed": true
}

#           #
#   NOTES   #
#           #

###

POST https://localhost:3000/notes/group HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

{
    "name": "TEST Note Group 2",
    "text": "TEST"
}

###

GET https://localhost:3000/notes/group HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

GET https://localhost:3000/notes/group/602aa0314b77ef505c08a12c HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

DELETE https://localhost:3000/notes/group/602aa0314b77ef505c08a12c HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

PATCH https://localhost:3000/notes/group/602aa0314b77ef505c08a12c HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

{
    "name": "11111",
    "text": "22222",
    "time": "00:10:00",
    "completed": true
}

#                 #
#   NOTE GROUPS   #
#                 #

###

POST https://localhost:3000/notes/group/602a8c30a8b8b2028c1d628e/notes HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

{
    "name": "TEST Note",
    "text": "TEST"
}

###

GET https://localhost:3000/notes/group/602a8c30a8b8b2028c1d628e/notes HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

GET https://localhost:3000/notes/group/602a8c30a8b8b2028c1d628e/notes/note/602a925594ae6a242a7f936e HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

DELETE https://localhost:3000/notes/group/602a8c30a8b8b2028c1d628e/notes/note/602a925594ae6a242a7f936e HTTP/1.1
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

###

PATCH https://localhost:3000/notes/group/602a8c30a8b8b2028c1d628e/notes/note/602a925594ae6a242a7f936e HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3AXRRnbtYQLrMAnzRfm_vVHvIyboD0RdbY.eGG6ueLIvX7o8X1M2OAXeHp1xYr%2FtZPdKqRZY4BygKU

{
    "name": "11111",
    "text": "22222"
}


#              #
#   Projects   #
#              #

###

POST https://localhost:3000/projects HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3ARJ3v5goxiYo1FO_cOLFSIJcF4Y52J9d6.fXDQDFVDL2IovrAEEtZ9SMLi9gE4ZBJaxwvCQWeKsX0

{
    "name": "TEST Project",
    "text": "TEST"
}

###

GET https://localhost:3000/projects HTTP/1.1
Cookie: connect.sid=s%3ARJ3v5goxiYo1FO_cOLFSIJcF4Y52J9d6.fXDQDFVDL2IovrAEEtZ9SMLi9gE4ZBJaxwvCQWeKsX0

###

GET https://localhost:3000/projects/602c8d2ff9526c1d84a28fa6 HTTP/1.1
Cookie: connect.sid=s%3ARJ3v5goxiYo1FO_cOLFSIJcF4Y52J9d6.fXDQDFVDL2IovrAEEtZ9SMLi9gE4ZBJaxwvCQWeKsX0

###

DELETE https://localhost:3000/projects/602c8d2ff9526c1d84a28fa6 HTTP/1.1
Cookie: connect.sid=s%3ARJ3v5goxiYo1FO_cOLFSIJcF4Y52J9d6.fXDQDFVDL2IovrAEEtZ9SMLi9gE4ZBJaxwvCQWeKsX0

###

PATCH https://localhost:3000/projects/602c8d2ff9526c1d84a28fa6 HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3ARJ3v5goxiYo1FO_cOLFSIJcF4Y52J9d6.fXDQDFVDL2IovrAEEtZ9SMLi9gE4ZBJaxwvCQWeKsX0

{
    "name": "11111",
    "text": "22222"
}

#                      #
#   Projects Planner   #
#                      #

###

POST https://localhost:3000/projects/602c8d2ff9526c1d84a28fa6/planner/meeting HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3ARJ3v5goxiYo1FO_cOLFSIJcF4Y52J9d6.fXDQDFVDL2IovrAEEtZ9SMLi9gE4ZBJaxwvCQWeKsX0

{
    "name": "TEST MEETING",
    "text": "FROM PROJECT",
    "datetime": "2021-02-20T00:00:00",
    "completed": false
}

###

GET https://localhost:3000/projects/602c8d2ff9526c1d84a28fa6/planner/meeting  HTTP/1.1
Cookie: connect.sid=s%3ARJ3v5goxiYo1FO_cOLFSIJcF4Y52J9d6.fXDQDFVDL2IovrAEEtZ9SMLi9gE4ZBJaxwvCQWeKsX0

###

GET https://localhost:3000/projects/602c8d2ff9526c1d84a28fa6/planner/meeting/602c8e6a6252d020db3cbd1d  HTTP/1.1
Cookie: connect.sid=s%3ARJ3v5goxiYo1FO_cOLFSIJcF4Y52J9d6.fXDQDFVDL2IovrAEEtZ9SMLi9gE4ZBJaxwvCQWeKsX0

###

DELETE https://localhost:3000/projects/602c8d2ff9526c1d84a28fa6 HTTP/1.1
Cookie: connect.sid=s%3ARJ3v5goxiYo1FO_cOLFSIJcF4Y52J9d6.fXDQDFVDL2IovrAEEtZ9SMLi9gE4ZBJaxwvCQWeKsX0

###

PATCH https://localhost:3000/projects/602c8d2ff9526c1d84a28fa6 HTTP/1.1
content-type: application/json
Cookie: connect.sid=s%3ARJ3v5goxiYo1FO_cOLFSIJcF4Y52J9d6.fXDQDFVDL2IovrAEEtZ9SMLi9gE4ZBJaxwvCQWeKsX0

{
    "name": "11111",
    "text": "22222"
}